base:
   mean: 
      - 0.485
      - 0.456
      - 0.406
   std: 
      - 0.229
      - 0.224
      - 0.225
   device: 'cpu'
   in_channel: 3
   height: 32
   width: 100
   train_rate: 0.9
   train: True
   pretrained: True
   load_path: 'checkpoints/crc_checkpoints/20211108/20211108_25898_resnet_rnn.pt'
   characters: '-0123456789abcdefghijklmnopqrstuvwxyz'

train:
  batch_size: 128
  input_path: '/Disk/hsj/dataset/train'
  multi: True
  checkpoints_path: 'checkpoints/resnet_rnn_ctc'
  early_stop: 50
  valid_interval: 2
  epochs: 500
  keep_ratio: True

test:
  batch_size: 32
  input_path: '/Disk/hsj/dataset/test'
  output_path: 'resnet_rnn_ctc'
  multi: True
  keep_ratio: True

base_model: 'CRNN'

model:
  name: 'resnet_rnn_ctc'
  cnn: 'ResNet'
  rnn: 'lstm'
  map_to_seq_hidden: 1024
  rnn_hidden: 128
  rnn_num_layers: 2
  num_class: 37

loss:
  decode_method: "beam_search"
  beam_size: 10
  center_loss: False


optimizer:
  momentum: 0.9
  base_lr: 0.001
  milestones: 
    - 30
    - 100
  gamma: 0.1
  

  


  
  
  

   
   
